// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWxCv_TGNKGtCZN7uY1D6WyIOOZ3GlBDw',
    appId: '1:346540608375:web:80db94497461e5c27d2f72',
    messagingSenderId: '346540608375',
    projectId: 'beezy-e0e2b',
    authDomain: 'beezy-e0e2b.firebaseapp.com',
    storageBucket: 'beezy-e0e2b.appspot.com',
    measurementId: 'G-JNHE86LYNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rLiMhGf66jpw-rlIDGD_5a9M0v7I5Xo',
    appId: '1:346540608375:android:f3ad0afc4dc913f77d2f72',
    messagingSenderId: '346540608375',
    projectId: 'beezy-e0e2b',
    storageBucket: 'beezy-e0e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuqwnD92lZ-BpTIdxz-MyG9W5mJPqhoc',
    appId: '1:346540608375:ios:2ddac2ae45cdbab67d2f72',
    messagingSenderId: '346540608375',
    projectId: 'beezy-e0e2b',
    storageBucket: 'beezy-e0e2b.appspot.com',
    iosBundleId: 'com.example.beezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuqwnD92lZ-BpTIdxz-MyG9W5mJPqhoc',
    appId: '1:346540608375:ios:eb0d3cdb9e4fe4be7d2f72',
    messagingSenderId: '346540608375',
    projectId: 'beezy-e0e2b',
    storageBucket: 'beezy-e0e2b.appspot.com',
    iosBundleId: 'com.example.beezy.RunnerTests',
  );
}
